name: django-tutorial
services:
  postgres:
    build:
      context: .
      dockerfile: Docker/postgres.dockerfile
    image: "postgres-tutorial"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - tutos:/data/postgres-tuto
    ports:
      - "5432:5432"
    restart: unless-stopped
  django-api:
    build:
      context: .
      dockerfile: Docker/django.dockerfile
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "8000:8000"
    env_file:
      .env
    restart: unless-stopped
volumes:
  tutos:
    external: true