name: django_rest
services:
  db:
    build:
      context: .
      dockerfile: Docker/postgres.dockerfile
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      HOST: ${HOST}
    healthcheck:
      test: ["CMD", "psql", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - tutos:/data/postgres-tuto
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: unless-stopped


  api:
    build:
      context: ./src
      dockerfile: django.dockerfile
    container_name: django
    depends_on:
      - db
    #     condition: service_healthy
    # volumes:
    #   - .:/src
    ports:
      - "8000:8000"
    env_file:
      .env
    restart: unless-stopped

volumes:
  tutos:
    external: true